services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      - POSTGRES_USER=my-postgres-user
      - POSTGRES_PASSWORD=pwd123
      - POSTGRES_DB=my-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
